{% set version = "6.1.26" %}

package:
  name: libdb
  version: {{ version }}

source:
  url: http://download.oracle.com/berkeley-db/db-{{ version }}.tar.gz
  sha256: dd1417af5443f326ee3998e40986c3c60e2a7cfb5bfa25177ef7cadb2afb13a6
  patches:
    # fixes atomic issue on clang, see https://trac.macports.org/ticket/53577#no1
    - src_dbinc_atomic.h.patch  # [osx]

build:
  number: 2002
  skip: True  # [unix or vc<14]

# NOTE: on windows, there's a very strange set of build issues.
#     If you run the VS2008 build, you need to do so as a normal user, or else you get permission errors on the TEMP folder.
#     If you run the VS2015 build, you need to run it from an elevated prompt, or else you get errors like:
#           C:\Program Files
#           (x86)\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(219,5):
#           error MSB4036: The "SetEnvironmentVariable" task was not found.
#           Check the following: 1.) The name of the task in the project file is
#           the same as the name of the task class. 2.) The task class is
#           "public" and implements the Microsoft.Build.Framework.ITask
#           interface. 3.) The task is correctly declared with <UsingTask> in
#           the project file, or in the *.tasks files located in the "C:\Program
#           Files (x86)\MSBuild\14.0\bin" directory.
#           [C:\ci\libdb_1537814475445\work\build_windows\VS10\db.vcxproj]

  run_exports:
    # OK for minor
    # https://abi-laboratory.pro/?view=timeline&l=libdb
    - {{ pin_subpackage("libdb", max_pin="x.x") }}

requirements:
  build:
    - make                  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.oracle.com/technology/software/products/berkeley-db/index.html
  license: AGPL-3.0
  license_file: LICENSE
  summary: 'The Berkeley DB embedded database system.'

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
