travis:
  secure:
    BINSTAR_TOKEN: KQUMdYN96nX/Kxh/XCbFwOyP+4EmSoO98ZxXX7Qny4SGIF0f8l9HGGn5VxG3QkJl52ZJ00lqJUJcivsOm2GkMaVCIPteaWXYPLZmMExvzCkjE42k5Sy36gpp/1P0Wgxq0IlLCcOcimgQR++lIviVv3Yg4t/OTKDm381xh69XwokZhLBZ/iOsEJVpmghhHHSulNF2wvSB1D+nA4WWazPCe1fu5fv0NDGeeY99Ws5OQ8QXHHzuMl2zVpTdCWefZBMhTvRW+OUhujlC2K24r6hnTv7xDV2tco/ryUPAhZI9fIQwby9yCEzz15jZujNR7G5QUP0ISBM45b6vItwgcr3gIlQkgkTkkb6nFC2y3z73H4NNCKql3V6GJ0aoaLidXwt9wceKWyw+owiUgqDbgPInruCQREZEm/yocpTdrjqtnzeJHSzf+IWnt/CjNT6Llgj2ch4bsqWvw9DWDdS4BIF4XTww2dgfDYKdECiKOBHboIC8Uajvmuyc6vIScphjd85lGyG2enta9NyTwfPVoqkRduEFNjmchfK8Q8MjpDI0YSJVLvSU6rXahJxvOX+MNWt/c/O69VA2lU3cXCznoOImMBjzA2fpZXeOe9yzd53aMjaQhx/+HZFpj6WSvYcQdh8QLSfXFAW/G2lThFfPAVuoKRDXClIpy8TuXkngJZAd5Bw=
appveyor:
  secure:
    BINSTAR_TOKEN: hhS98dVbKVMiq1d7IEUyMCfA9Be1YSA2+BfDYf+1wwLYdOoWLWVaehGr6/mjqeAv

channels:
  sources: [defaults, conda-forge]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: libdb-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank
